---
- hosts: all
  become: true
  vars:
    admin_ip: 192.168.56.104
    users_network: 192.168.56.103
    printer_ip: 192.168.56.108
  
- hosts: admin
  become: true
  roles:
      - docker

- hosts: users
  become: true
  roles:
      - container
      - firewall
      - set_roles
