---
- name: Create Docker network
  community.docker.docker_network:
    name: "{{ users_network }}"
    state: present

- name: Deploy admin container
  community.docker.docker_container:
    name: admin
    image: admin-image:latest
    networks:
      - name: "{{ users_network }}"
    restart_policy: always
    state: started

- name: Deploy device container
  community.docker.docker_container:
    name: user
    image: user-image:latest
    networks:
      - name: "{{ users_network }}"
    restart_policy: always
    state: started

- name: Deploy printer container
  community.docker.docker_container:
    name: printer
    image: printer-image:latest
    networks:
      - name: "{{ users_network }}"
    restart_policy: always
    state: started
